version: "2"
exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/.storybook/"
  - "**/deprecated/"
  - "**/webpack"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "**/*.stories.*"
  - "**/*.config.*"
